### ISSUE TITLE
Can't ligma

### ISSUE THREAD

**Issue by getItemFromBlock** [Motisma479/GOL#1]
Can't open or compile the project, as there is no .vs file in the repo
Note : I am on the C++_ScreenSaver branch

**Comment by getItemFromBlock** [comment]
Also Releases are missing

**Comment by Motisma479** [comment]
The .vs/ is not required to lauch the visual studio project launch the .sln  with <ins>__Visual Studio 2022__</ins>. The releases will soon be available.
